### ISSUE TITLE
Task: Create acceptance test for Assignments page.

### ISSUE THREAD

**Issue by amczuboka** [amczuboka/Decagon-CondoManagementSystem#44] opened 2024-01-29 19:27 UTC
#34

**Comment by amczuboka** [comment] 2024-01-29 20:30
Test linked to Task #39

**Comment by npiperni** [comment] 2024-03-21 16:49
https://github.com/amczuboka/Decagon-CondoManagementSystem/issues/39#issuecomment-1982125612
duplicate of #43

**Closed by npiperni** 2024-03-21 16:49 UTC
Labels: Testing, #15, SP: 2
